"""Frozen scientific-setting registration and sidecar validation."""

from chemsmart.agent.harness.scientific_settings.contracts import (
    EvidenceCeilingV1,
    LoaderObservation,
    RendererObservation,
    ScientificProgram,
    ScientificSettingsOverlayV1,
    ScientificSettingsRegistryV1,
    ScientificSettingsValidationReceiptV1,
    SettingCapabilityV1,
    SettingEvidenceSourceV1,
    SettingMatchKind,
    SettingResolutionStatus,
    SettingResolutionV1,
    canonical_contract_json,
    content_sha256,
    normalize_setting_literal,
    scientific_setting_resolution_sha256,
    scientific_settings_overlay_sha256,
    scientific_settings_receipt_sha256,
    scientific_settings_registry_sha256,
)
from chemsmart.agent.harness.scientific_settings.registry import (
    build_scientific_settings_validation_receipt,
    list_scientific_settings,
    load_scientific_settings_registry,
    resolve_scientific_setting,
    validate_scientific_settings_source_snapshot,
)

__all__ = [
    "EvidenceCeilingV1",
    "LoaderObservation",
    "RendererObservation",
    "ScientificProgram",
    "ScientificSettingsOverlayV1",
    "ScientificSettingsRegistryV1",
    "ScientificSettingsValidationReceiptV1",
    "SettingCapabilityV1",
    "SettingEvidenceSourceV1",
    "SettingMatchKind",
    "SettingResolutionStatus",
    "SettingResolutionV1",
    "build_scientific_settings_validation_receipt",
    "canonical_contract_json",
    "content_sha256",
    "load_scientific_settings_registry",
    "list_scientific_settings",
    "normalize_setting_literal",
    "resolve_scientific_setting",
    "scientific_setting_resolution_sha256",
    "scientific_settings_overlay_sha256",
    "scientific_settings_receipt_sha256",
    "scientific_settings_registry_sha256",
    "validate_scientific_settings_source_snapshot",
]
